### ISSUE TITLE
Inconsistency with KDE maximize

### ISSUE THREAD

**Issue by Self-Perfection** [lucmos/UltrawideWindows#20]
UltrawideWindows does not play nice with KDE native "maximized window" concept. It is subtle but noticable. Placing maximized window somewhere with UltrawideWindows seems to retain window "maximized" flag. For instance:

* Let's say I press <kbd>Meta</kbd> + <kbd>Numpad6</kbd> with maximized window active. Window takes rightmost third position. Let's say I press then standard kwin hotkey for toggling maximized state <kbd>Meta</kbd> + <kbd>Page Up</kbd>. Window does get maximized again as expected, but instead moves to its un-maximized place. To actually miximize window one have to press <kbd>Meta</kbd> + <kbd>Page Up</kbd> again.
* If desktop effects are turned on un-maximized windows have shadow around their borders. Maximized windows do not drop shadow because it would be outside of screen bounds and therefore invisible. But after moving maximized window somewhere with UltrawideWindows hotkey window does not have shadow around its border. Seems that kwin in unaware that window is not maximized anymore. But slightly resizing the window makes kwin aware of un-maximized state and border appears.

**Comment by MartijnVogelaar** [comment]
I have actually come across the same problem while using Latte-Dock's window buttons. I made a fork fixing it but never bothered to make a pull request but I've made one now. This most likely fixes your problem as well, feel free to give it a try. 

https://github.com/lucmos/UltrawideWindows/pull/24

**Comment by lucmos** [comment]
I merged the PR that solves this. Let me know if the issue persists for you!

**Comment by Self-Perfection** [comment]
24 actually broke moving of maximized windows but I managed to fix it in #25
