### ISSUE TITLE
No effect on Kubuntu 20.04

### ISSUE THREAD

**Issue by martinmagnusson** [lucmos/UltrawideWindows#37]
What are the KDE/plasma requirements for these scripts? On my Kubuntu 20.04 installation, none of the scripts seem to have any effect. (I also tried changing the keybindings.) KDE Plasma v 5.18.8, Frameworks 5.68.0, Qt 5.12.8.

**Comment by lucmos** [comment]
I just tried with a fresh installation of an up-to-date plasma and it seems to work fine!

I am installing it with:

```
git clone git@github.com:lucmos/UltrawideWindows.git
cd UltrawideWindows
plasmapkg2 --type=kwinscript -i .
```
