### ISSUE TITLE
Script stopped working after latest update of Plasma

### ISSUE THREAD

**Issue by eliaskaerle** [lucmos/UltrawideWindows#40]
Hey,
after the latest update of KDE Neon, the script stopped working. Can any idea how I get this awesome script back?
Thanks
![image](https://github.com/lucmos/UltrawideWindows/assets/1135542/f0b61d44-12ad-4b7a-a36f-3243fedf3f27)

**Comment by alex-voodoo** [comment]
Out of curiosity, did you use Wayland before this last update?

**Comment by eliaskaerle** [comment]
I don't think so tbh. X11 was the default and it switched to Wayland only with version 6, right?

**Comment by alex-voodoo** [comment]
That is likely the reason.  This UltrawideWindows relies on some features of X11 which are not present in Wayland, and are not going to, unless the Plasma team decides to implement them (and even if they do, it will be the Wayland way).

**Comment by eliaskaerle** [comment]
Oh dear... why didn't I think about that myself :sweat_smile: 
Thanks a lot for that hint. I'm going to close this issue, but before, one last question: do you know anything like this AWESOME script that works with Wayland?

**Comment by alex-voodoo** [comment]
No, unfortunately I don't, and that is why I will stay on X11 as long as I can.

**Comment by eliaskaerle** [comment]
That's a pity... then I am going to switch back to X11, too. Thanks again for your help!

**Comment by cyberang3l** [comment]
Had the same issue. Spent sometime today and figured it out. Created a PR: #41

**Comment by eliaskaerle** [comment]
Amazing!!! Thanks a lot @cyberang3l !
