### ISSUE TITLE
Move to right-height 4x2 uses 2 slots instead of one

### ISSUE THREAD

**Issue by sharhalakis** [lucmos/UltrawideWindows#8]
Ctrl+Meta+Num+6 uses 2/4 horizontal slots instead of 1/4.

Can you please update the code to use 1?

I.e. this:

```
registerShortcut("MoveWindowToRightHeight4x2_centerbiased", "UltrawideWindows: Move Window to right-height (4x2 center biased)", "Ctrl+Meta+Num+6", function () {
    move(workspace, 4, 1, 3, 0, 2, 1)
});
```

needs to have `move(workspace, 4, 1, 3, 0, 1, 1)`

**Comment by lucmos** [comment]
Hi,

If I'm not mistaken on `master` I already fixed it

https://github.com/lucmos/UltrawideWindows/blob/10bc8d02178503302070dd884e1e01d5390046f4/contents/code/main.js#L171-L172

**Comment by sharhalakis** [comment]
Great! In that case this is then a request to push a new version to store.kde.org :)

**Comment by lucmos** [comment]
Ok, I bumped the version and published it on the store!
